# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ] 


jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: | 
          8.0.x
          9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Send mail
      uses: dawidd6/action-send-mail@v6
      #env:
      # Optional http proxy:
      # HTTP_PROXY: http://proxy.example.test:3128
      with:
        connection_url: ${{secrets.MAIL_CONNECTION}}
        # Required mail server address if not connection_url:
        server_address: ${{secrets.SECRET_HOST}} 
        # Server port, default 25:
        server_port: ${{secrets.SECRET_PORT}}
        # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: false
        # Optional (recommended) mail server username:
        username: ${{secrets.SECRET_LOGIN}}
        # Optional (recommended) mail server password:
        password: ${{secrets.SECRET_PASS}}
        # Required mail subject:
        subject: Prueba de Workflow
        # Required recipients' addresses:
        to: obiwan@example.com,yoda@example.com
        # Required sender full name (address can be skipped):
        from: Luke Skywalker <facuq240@gmail.com>
        # Optional plain body:
        body: Build job of ${{github.repository}} completed successfully!
        # Optional unsigned/invalid certificates allowance:
        ignore_cert: true
        # Optional converting Markdown to HTML (set content_type to text/html too):
        convert_markdown: true
        # Optional attachments:
        attachments: attachments.zip,git.diff,./dist/static/*.js
        # Optional priority: 'high', 'normal' (default) or 'low'
        priority: low

