# Entrega 2
name: GH-build-DEV.yml

on:
  push:
    branches: [ "main" ] 
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: | 
          8.0.x
          9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Send mail
      uses: dawidd6/action-send-mail@v6
      with:
        server_address: ${{secrets.EMAIL_HOST}}     # ej: smtp.debugmail.io
        server_port: ${{secrets.EMAIL_PORT}}        # ej: 25 o 587
        username: ${{secrets.EMAIL_USER}}          # tu usuario de DebugMail
        password: ${{secrets.EMAIL_PASS}}           # tu contraseña de DebugMail
        subject: Prueba de Workflow Quiroga Facundo
        to: obiwan@example.com,yoda@example.com
        from: Luke Skywalker luke@skywalker.com.ar # Puede ser cualquier cosa
        body: Build job of ${{github.repository}} completed successfully! 
